### PR TITLE
Update dpdk_netperf app to compile with DPDK 22.03

### PR DESCRIPTION
**Pull request by andreybleme**
Some attributes of the [rte__ether__hdr](https://doc.dpdk.org/api-22.03/structrte__ether__hdr.html) struct are deprecated. This is causing the `dpdk_netperf` app fail to compile with recent versions of DPDK.

Some of the erros found when trying to compile the `dpdk_netperf` app using DPDK 22.03.

```
../examples/dpdk_netperf/dpdk_netperf.c:274:48: error: ‘struct rte_ether_hdr’ has no member named ‘s_addr’; did you mean ‘dst_addr’?
  274 |         rte_ether_addr_copy(&my_eth, &eth_hdr->s_addr);

../examples/dpdk_netperf/dpdk_netperf.c:30:18: error: ‘struct rte_eth_rxmode’ has no member named ‘max_rx_pkt_len’; did you mean ‘max_lro_pkt_size’?
   30 |                 .max_rx_pkt_len = RTE_ETHER_MAX_LEN
```

Here is the latest version of `rte_ether_hdr`, from the DPDK source:
https://github.com/DPDK/dpdk/blame/fab31a03ba98e7457284df95dd9eef2223a4ccaa/lib/net/rte_ether.h#L300
https://github.com/DPDK/dpdk/blob/fab31a03ba98e7457284df95dd9eef2223a4ccaa/lib/ethdev/rte_ethdev.h#L427

### CODE REVIEW

File: apps/dpdk_netperf/dpdk_netperf.c [hunk 1]
```diff
@@ -27,7 +27,7 @@
 
 static const struct rte_eth_conf port_conf_default = {
 	.rxmode = {
-		.max_rx_pkt_len = RTE_ETHER_MAX_LEN,
+		.max_lro_pkt_size = RTE_ETHER_MAX_LEN,
```
[the remark this answers is not in the document]
Comment (andreybleme) [reply apps/dpdk_netperf/dpdk_netperf.c]: Yea, make sense. I have updated it.
